        
        //public class PenSet
        //{
        //    public Pen Default = Pens.Black;
        //    public Pen My { get; set; }
        //    public Pen Friendly { get; set; }
        //    public Pen Hostile { get; set; }

        //    public Pen Select(Ship OwnShip, Ship ship)
        //    {
        //        if (ship == OwnShip)
        //            return My;
        //        if (OwnShip != null && ship.Nation == OwnShip.Nation)
        //            return Friendly;
        //        if (OwnShip != null && ship.Nation != OwnShip.Nation)
        //            return Hostile;
        //        return Default;
        //    }
        //}

        //public class BrushSet
        //{
        //    public Brush Default = Brushes.Black;
        //    public Brush My { get; set; }
        //    public Brush Friendly { get; set; }
        //    public Brush Hostile { get; set; }

        //    public Brush Select(Ship OwnShip, Ship ship)
        //    {
        //        if (ship == OwnShip)
        //            return My;
        //        if (OwnShip != null && ship.Nation == OwnShip.Nation)
        //            return Friendly;
        //        if (OwnShip != null && ship.Nation != OwnShip.Nation)
        //            return Hostile;
        //        return Default;
        //    }
        //}
